---
filters:
  - filters/expand-prefixes.lua

format:
  html:
    anchor-sections: true
    axe: true
    grid:
      body-width: 1200px
    # include-in-header:
    #   - _includes/dokieli.html
    minimal: true
    link-external-icon: false
    link-external-newwindow: true
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    smooth-scroll: true

kernel: .venv

project:
  type: website
  post-render:
    - scripts/postrender.py
  pre-render:
    - scripts/prerender.py

website:
  title: Adriano Rutz
  description: Personal website of Adriano Rutz
  site-path: ./
  site-url: https://adafede.github.io
  favicon: images/favicon/favicon.ico
  repo-url: https://github.com/adafede/adafede.github.io
  search:
    location: navbar
  open-graph:
    locale: en
    site-name: https://adafede.github.io
  navbar:
    left:
      - text: Articles
        aria-label: Articles
        href: articles.qmd
      - text: CV
        aria-label: Curriculum vit√¶
        href: cv.qmd
      - text: Posts
        aria-label: Posts
        href: posts.qmd
      - text: Talks
        aria-label: Talks
        href: talks.qmd
      - text: Teaching
        aria-label: Teaching
        href: teaching.qmd
      - text: Varia
        aria-label: Varia
        href: varia.qmd
    right:
      - icon: rss
        href: rss.xml
  body-header: |
    <script async src="https://scripts.simpleanalyticscdn.com/latest.js">
    </script>
